
services:
  
  app:

    image: pereira00/formula1api:lewis
    depends_on:
      - db
    restart: always
    container_name: f1-app
    ports:
      - "3000:5001"
    environment:
      SERVER : ${SERVER}
      BD : ${BD}
      USERBD : ${USERBD}
      PASSWORD : ${PASSWORD}

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
    container_name: ${SERVER}
    volumes:
      - bd-f1:/var/opt/mssql

volumes:
  bd-f1:
    external: false
